version: '2'
services:
  testmongo:
    image: mongo:latest
    command: mongod --smallfiles --quiet
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
    ports:
      - "27017:27017"

  app:
    depends_on:
      - 'testmongo'
      # - 'redis'
    build: .
    ports:
      - '3000:3000'
    #volumes:
    #  - '.:/app'
    command: rails server -p 3000 -b '0.0.0.0'
    
volumes:
  testmongo:     